name: Deploy Flask To-Do App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Copy Files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: fzansari
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "*"
        target: "/home/fzansari/Python-Bootcamp/ToDo"

    - name: SSH and Restart Gunicorn
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: fzansari
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/fzansari/Python-Bootcamp/ToDo
          python3 -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pkill gunicorn || true
          nohup venv/bin/gunicorn --bind 0.0.0.0:5000 wsgi:app &
          # sudo systemctl restart gunicorn ${{secrets.SUDOPWD }}

